[package]
name = "e1000"
version = "0.1.0"
license = "GPL-3.0-or-later"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
derive_more = "0.99.17"
futures = "0.3.21"
redshirt-ethernet-interface = { path = "../../interface-wrappers/ethernet" }
redshirt-hardware-interface = { path = "../../interface-wrappers/hardware" }
redshirt-pci-interface = { path = "../../interface-wrappers/pci" }
redshirt-syscalls = { path = "../../interface-wrappers/syscalls" }
redshirt-time-interface = { path = "../../interface-wrappers/time" }
smallvec = "1.8.0"
