# Note: this file exists in order to provide a more convenient development environment in the
# redshirt repository. It is not mandatory to put a similar file next to programs developed for
# redshirt. The redshirt programs builder automatically makes sure (in `redshirt-core`) makes sure
# that the module is built with the appropriate options.

[build]
target = "wasm32-wasip1"

[target.'wasm32-wasip1']
rustflags = ["-C", "link-arg=--export-table", "-C", "link-arg=--import-memory"]
